bnb-chain/docs-site

docs/api-reference/dex-api/paths.md
swagger.yml

add body: {"code":404,"message":"account not found"} for account not found response
**Example**
https://testnet-dex-asiapacific.binance.org/api/v1/account/tbnb10qpmrlsr4mq65xwgjd39xypkkpw3wm9c5e58xm
body: {"code":404,"message":"account not found"}
status code is still 404

add error msg to account not found

---

docs/trading-spec.md

Add explanations for order lifecycle

add lifecycle

---

docs/ownbit.md

Add Ownbit

---

docs/fullnode.md
docs/fullnodeissue.md
docs/memo-validation.md
docs/resources.md
mkdocs.yml

- remove extra TOC in docs
- Improve search index
- Clean up some docs

Improve research and clean up

---

docs/walletconnect-support.md
docs/wallets.md

This PR updates `walletconnect-support.md` and `wallets.md` for Cosmostation Wallet

Update docs for Cosmostation

---

docs/wallets.md
docs/wallets/dcent-wallet.md

Hi!
I'd like to add D'CENT biometric wallet into binance chain docs site.
D'CENT biometric wallet already supports Binance Chain.
https://dcentwallet.com/products/BiometricWallet

Add D'CENT wallet

---

docs/smart-chain/wallet/AlphaWallet.md

AlphaWallet Binance Smart Chain supports will be in the next release
Andriod Test APK
https://drive.google.com/file/d/1zzTRlRcj1oDAVa1eYjqxirgLmxa4bGLx/view?usp=sharing

AlphaWallet Binance Smart Chain supports

---

docs/faq/bsc/eco.md

Please add BSCswap.com for the BSC ecosystem please

Add BSCswap on the list

---

docs/faq/bsc/eco.md

drop specific project names

---

docs/smart-chain/guides/panama.md

This is a small grammar fix for the Documentation.

doc: Grammar. Replace "In Conclude" to "In Conclusion".

---

docs/smart-chain/wallet/trustwallet.md

This is a simple guide on how to get started using Trust Wallet for Binance Smart Chain.

created trustwallet.md

---

mkdocs.yml

Already created the trustwallet.md file.
Adding it to mkdocs.yml for it to show up under BSC wallets.

edit mkdocs.yml to add Trust Wallet

---

docs/wallets/bsc-wallets.md

adding Trust Wallet tutorial to this list:
https://docs.binance.org/wallets/bsc-wallets.html

add Trust Wallet to BSC Wallets

---

docs/guides/testnet.md

fix faucet description

---

docs/smart-chain/developer/link.md

- Updated content & code snippets to AggregatorV3Interface
- Tidied up structure
- Added Mainnet feed address.

Doc: Update Chainlink Price Feeds

---

docs/smart-chain/developer/rpc.md

```
http://data-seed-prebsc-1-s2.binance.org:8545/	
http://data-seed-prebsc-2-s2.binance.org:8545/
```
==> 
```
https://data-seed-prebsc-1-s2.binance.org:8545/	
https://data-seed-prebsc-2-s2.binance.org:8545/
```

[R4R]fix scheme error for BSC node on testnet

---

docs/smart-chain/wallet/metamask.md

Some grammar mistakes and typos

Corrected typo "MetakMast" and more

---

docs/smart-chain/developer/oracle/dia.md

PR with the first version of the documentation about the DIA oracle on BSC Testnet.

Add first DIA oracle documentation version

---

docs/faq/bsc/val.md

Fix typo in /faq/bsc/val.md

---

docs/smart-chain/developer/deploy/truffle.md

adjust hdwallet-provider and add sample solidity version compiler

adjust hdwallet-provider

---

docs/smart-chain/developer/upgrade/proxy.md

Hello 👋
Fixed while reading, great docs btw!

Fixed Proxy.md

---

docs/api-reference/dex-api/paths.md
docs/changelog.md
swagger.yml

Reverts binance-chain/docs-site#488

Revert "Api changelog"

---

docs/smart-chain/wallet.md
docs/smart-chain/wallet/infinitywallet.md
docs/walletconnect-support.md
docs/wallets.md
docs/wallets/infinitywallet.md
docs/wallets/walletconnect-support.md
docs/wallets/wallets.md

We have added the Infinity Wallet to the Binance Chain, Binance Smart Chain & Wallet Connect lists of supporting wallets, as well as created the individual information pages for the wallet.

Added Infinity Wallet to BC & BSC Supported Wallets

---

docs/api-reference/dex-api/paths.md

update rate limit

---

docs/smart-chain/developer/fullnode.md

1. update the bsc release to v1.1.5
2. Add the Node Maintainence part

[R4R]update to v1.1.5

---

docs/smart-chain/developer/fullnode.md

Specified requirements of fullnode and validator updated.

Fullnode and Validator Requirements Update

---

docs/smart-chain/guides/cross-chain.md

Hello, AtomicDEX offers bridges between BEP20 and more than 20 different protocols on mobile, desktop & CLI

Adding AtomicDEX in the list of cross-chain

---

docs/smart-chain/developer/BSC-mainnet-explorers.md
docs/smart-chain/developer/BSC-testnet-explorers.md
docs/smart-chain/developer/bind/bind-tokens.md
docs/smart-chain/developer/cross-chain-tech.md
docs/smart-chain/developer/deploy/hardhat-new.md
docs/smart-chain/developer/deploy/local.md
docs/smart-chain/developer/deploy/truffle-new.md
docs/smart-chain/developer/deploy/verify.md
docs/smart-chain/developer/dev-tools.md
docs/smart-chain/developer/issue-BEP20.md
docs/smart-chain/developer/upgrade/proxy.md
docs/smart-chain/guides/bsc-intro.md
docs/smart-chain/guides/concepts/incentives.md
docs/smart-chain/guides/cross-chain.md
docs/smart-chain/wallet.md
docs/smart-chain/wallet/bitkeep.md
mkdocs.yml

updated navbar and md files for better understanding and navigation

Changes to the doc

---

docs/smart-chain/developer/rpc.md

Added RPC Aggregator and link to public BSC RPC node

Issue #586 Update rpc.md

---

docs/guides/concepts/bsc-gov.md

submit-cscParam-change-proposal is the right sub command

fix: bscParam to cscParam
